version: '3.9'

services:
  java_db:
    container_name: db_spring_crud
    image: postgres:12
    ports:
      - 8054:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}